### PR TITLE
New learning paths

### PR DESCRIPTION
**Pull request by nikiljos**
- [x] Docker `/docker`
- [x] HTML,CSS,SASS `/html-css-sass`
- [x] Deep learning `/deep-learning`
- [x] SQL `/sql`
- [x] Ruby on rails `/ruby-on-rails`

Missing content
- Tags, Category not added

### CODE REVIEW

**Comment by LunaticHacker** [comment]
@nikiljos why are we forking? did tinkerhub decide to ditch the project?

**Comment by sreejithliterally** [comment]
Good job @nikiljos

**Comment by sreejithliterally** [comment]
> @nikiljos why are we forking? did tinkerhub decide to ditch the project?

We are updating this project.

**Review by sreejithliterally — APPROVED** [review]

**Comment by LunaticHacker** [comment]
@sreejithdikru  sorry to bother you again (too curious :laughing: ), but my question was on the rationale of the fork, why are we doing it here as opposed to the official repo?. Did tinkerhub stopped supporting the project?

**Comment by sreejithliterally** [comment]
@LunaticHacker We, the learning initiatives team of Tinkerhub decided to rearrange the existing website & For the ease of our work we forked it from the main repo. For some reasons we have to do it like this.I hope this will clear your doubt.😁 (Tinkerhub is still supporting the project)

**Pull request merged**
